# Generated by Django 3.2.25 on 2024-05-27 15:59
from django.contrib.auth import get_user_model
from django.db import migrations

def forwards_funk(apps, schema_editor):
    User = get_user_model()
    p = User(username='sad', is_staff=True, is_superuser=True)
    p.set_password('sad')
    p.save()

def backwards_funk(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_coments_comments'),
    ]

    operations = [
        migrations.RunPython(forwards_funk, backwards_funk),
    ]
